export const SPOTIFY_TOKENS = 'SPOTIFY_TOKENS';
export const REFRESH_ACCESSE_TOKEN = 'REFRESH_ACCESSE_TOKEN';

export const SPOTIFY_ME_SUCCESS = 'SPOTIFY_ME_SUCCESS';
export const SPOTIFY_ME_FAILURE = 'SPOTIFY_ME_FAILURE';

// export const ADD_SONG_TO_LIBRARY_SUCCESS = 'ADD_SONG_TO_LIBRARY_SUCCESS';
// export const ADD_SONG_TO_LIBRARY_ERROR = 'ADD_SONG_TO_LIBRARY_ERROR';

export const FETCH_PLAYLIST_MENU_PENDING = 'FETCH_PLAYLIST_MENU_PENDING';
export const FETCH_PLAYLIST_MENU_SUCCESS = 'FETCH_PLAYLIST_MENU_SUCCESS';
export const FETCH_PLAYLIST_MENU_ERROR = 'FETCH_PLAYLIST_MENU_ERROR';


export const FETCH_PLAYLIST_SONG_PENDING = 'FETCH_PLAYLIST_SONG_PENDING';
export const FETCH_PLAYLIST_SONG_SUCCESS = 'FETCH_PLAYLIST_SONG_SUCCESS';
export const FETCH_PLAYLIST_SONG_ERROR = 'FETCH_PLAYLIST_SONG_ERROR';

export const PLAY_SONG = 'PLAY_SONG';
export const STOP_SONG = 'STOP_SONG';
export const PAUSE_SONG = 'PAUSE_SONG';
export const RESUME_SONG = 'RESUME_SONG';